### ISSUE TITLE
I don't understand 'FILES_ROOT' 

### ISSUE THREAD

**Issue by Marcuzzz** [navatech/yii2-roxymce#1]
Hi,

I'm having trouble understanding 'FILES_ROOT'
If I use the default setting:
A folder is created at @backend/Users/"username"/"location"/"of"/"project"/backend/media/
(image: http://imgur.com/2aEA9ti)
It's a strange location of course but I can upload,delete files to this folder with roxymce
But when I try to preview a file for instance or use the widget, files will not view correctly because they need to be in the web folder.

So i've modified some of your code ending up with:
`$config['FILES_ROOT'] = '/web/media';`

and changed this:
//RoxyHelper.php
public static function getFilesPath() {
return FILES_ROOT;
}

It now shows me the full contents of the folder media located at the base of the website.
But unfortunately preview and widget still don't work correctly because now they are looking at /web/media instead of /media/ 

I'm a bit stuck, please help.
thx!

**Comment by Marcuzzz** [comment]
I managed to fix this by adding this to main.js:

```
function getSelectedFile() {
    var ret         = null;
    var pnlFileList = $('#pnlFileList').find('.selected');
    if(pnlFileList.length > 0) {
                // Added .replace('web/','')
        ret = new File(pnlFileList.attr('data-path').replace('web/',''));
    }
    return ret;
}
```

**Comment by phuongdev89** [comment]
Hi Marcuzzz,
Thanks for your report.
No need to fix main.js, just add a function to check basic or advanced kit & return match url

**Comment by Marcuzzz** [comment]
Yes, that would do it.
