### ISSUE TITLE
Is not installed

### ISSUE THREAD

**Issue by blackcat636** [navatech/yii2-roxymce#12]
![screenshot - 26 04 2017 - 10 53 31](https://cloud.githubusercontent.com/assets/8677920/25429932/55ada188-2a83-11e7-8371-8337cb0ee199.png)
navatech/yii2-roxymce dev-master requires bower-asset/tinymce-dist ^4.3 -> no matching package found.

**Comment by phuongdev89** [comment]
Hi @BlackCat636,  
`phamxuanloc/yii2-roxymce` is not maintenance by us  
It's 36 commits behind navatech:master  
please use newest release [here](https://github.com/navatech/yii2-roxymce/releases) or just remove folder `vendor` then run `composer update` again
