### ISSUE TITLE
Error to insert image to editor

### ISSUE THREAD

**Issue by drexlerux** [navatech/yii2-roxymce#13]
error to insert image to editor input:
![error mce](https://user-images.githubusercontent.com/29631825/30771498-bd271320-a00e-11e7-87d9-32d7f0269ea0.png)

**Comment by polinwei** [comment]
I got the same error. Who can help?

`Uncaught TypeError: Cannot set property 'value' of null
    at HTMLButtonElement.<anonymous> (roxy.js:291)
    at HTMLDocument.dispatch (jquery.js:4737)
    at HTMLDocument.elemData.handle (jquery.js:4549)
(anonymous) @ roxy.js:291
dispatch @ jquery.js:4737
elemData.handle @ jquery.js:4549`

**Comment by polinwei** [comment]
I selected a image , then click select . It does not do any action. fancybox is not close. image not pick it back.
