### ISSUE TITLE
Using without tinymce(not issue)

### ISSUE THREAD

**Issue by FarshidShekari** [navatech/yii2-roxymce#17]
Hi dear

I want to use this module in my project but you explained how to use very short.  I used [this ](https://github.com/navatech/yii2-roxymce/blob/master/docs/without.md)section but I couldn't get the result.
my code in my view:
`<div class="row"> 
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data'], 'action' => '#']); ?> 
<?= $form->field($model, 'thumb')->textInput(['id' => 'fieldID'])->label(false) ?> 
<a href="<?=Url::to([ 
'/roxymce/default', 
'type' => 'image', 
'input' => 'fieldID', 
'dialog' => 'fancybox', 
]) ?>"><i class="fa fa-upload"></i></a> 
<?php ActiveForm::end();?> 
</div>
<?php

$this->registerJsFile('@web/js/jquery.fancybox.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerCssFile('@web/css/jquery.fancybox.min.css', ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJs(' 
$("a").fancybox();  
', View::POS_END);
?>`
and I added a field(`thumb`) to `UploadForm` model that worked. but I can't upload any file. and this my question [link ](https://stackoverflow.com/questions/47526953/roxymce-file-manager-using-in-yii2/47527217#47527217)in stack. please help me to fix it.

**Comment by phuongdev89** [comment]
Hello, I saw your trouble, and have hot fix for it.  
Could you please try [this](https://github.com/navatech/yii2-roxymce/blob/master/docs/without.md) with new release version (2.0.5)? And tell me the result.  
Make sure your `thumb`'s id is the same as the id in the roxy link

![screenshot-github com-2017-11-29-13-15-28-879](https://user-images.githubusercontent.com/7648033/33360713-7872c836-d507-11e7-9a85-574fdbe649ae.png)

**Comment by FarshidShekari** [comment]
I update this module but when I have an error and I can't upload files. Like below image:

![sketch](https://user-images.githubusercontent.com/6597508/33379435-5b06fe68-d52d-11e7-86fa-5d5f3055de56.png)

This [link ](https://github.com/navatech/yii2-roxymce/blob/master/docs/without.md) load entire of index not in iframe [u can see in above picture- change address bar URL) and I want to know why you put **an input tag with type=text**  
@phuong17889

**Comment by alvarofvr** [comment]
What is the attribute `data-fancybox-type="iframe"`?

**Comment by phuongdev89** [comment]
@fantom0 could you please recheck your config? Can you show your project?(on github)
I put input tag with type=text because it is exactly why you need use filemanager without tinymce, roxy can only return the url of selected file
@alvarofvr please check fancybox docs here https://github.com/fancyapps/fancybox/blob/2.1/README.md

**Comment by FarshidShekari** [comment]
my main.php config file for module section have this setting:
```
 'modules' => [

        'roxymce' => [
            'class' => 'navatech\roxymce\Module',
            'uploadFolder' => '@app/web/uploads/images',
            'uploadUrl' => '/uploads/images',
        ],

    ],
```
my projct is in my local machine. I want to create this view just for upload files not select them.

**Comment by phuongdev89** [comment]
@fantom0 upload and not store or show them?
Could you please put your code of composer.lock here?

**Comment by FarshidShekari** [comment]
Upload but not save. 

[composer.zip](https://github.com/navatech/yii2-roxymce/files/1518727/composer.zip)

**Comment by phuongdev89** [comment]
@fantom0 seems your composer is ok, could you please share your project to github?

**Comment by FarshidShekari** [comment]
I can't, I used this [link](https://github.com/navatech/yii2-roxymce/blob/master/docs/without.md) but when  I click on a tag on my view entire page change but it doesn't open in `fancybox` in this image you can see it:
![33379435-5b06fe68-d52d-11e7-86fa-5d5f3055de56](https://user-images.githubusercontent.com/6597508/33485565-03316de6-d6bc-11e7-9d7b-84fc701edd42.png)

when my view load that's layout is:
![sketch](https://user-images.githubusercontent.com/6597508/33485694-925f8aca-d6bc-11e7-80a1-72aadc2fd0c3.png)
and after click link page entirely reload and redirect another page:
![sketch1](https://user-images.githubusercontent.com/6597508/33485729-b9c3b366-d6bc-11e7-803b-722bf2d56ea0.png)
In above picture don't show the preview of an image I manually put in that directory. and Why it display close and select button whereas we are at another URL?

**Comment by FarshidShekari** [comment]
and this is my view code:

```
<?php
use navatech\roxymce\assets\BootstrapTreeviewAsset;
use navatech\roxymce\assets\FancyBoxAsset;
use navatech\roxymce\assets\FontAwesomeAsset;
use navatech\roxymce\assets\LazyLoadAsset;
use yii\helpers\Url;
use yii\web\view;
FontAwesomeAsset::register($this);
LazyLoadAsset::register($this);
FancyBoxAsset::register($this);
BootstrapTreeviewAsset::register($this);
?>
<input type="text" id="fieldID">
<a class="fancybox" data-fancybox-type="frame" href="<?= Url::to([
    '/roxymce/default',
    'type'   => 'image',
    'input'  => 'fieldID',
    'dialog' => 'fancybox',
]) ?>">Click to show Roxy Filemanager</a>

<?=  $this->registerJs(' 
    $("#fileup").fancybox();
    ', View::POS_END);
        ?>

```

**Comment by FarshidShekari** [comment]
and my controller code for that view:
```
 public function actionUploadfile()
    {
        $model = new UploadForm();
        return $this->render('uploadfile',['model'=>$model]);
    }
```

**Comment by phuongdev89** [comment]
could you please try edit your `backend/config/main.php`
````
 'components' => [

  'assetManager' => [
    'bundles' =>[
      'yii\web\JqueryAsset' => [
        'js'         => [
          'https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js',
        ],
      ]
    ]
  ]

 ],
 'modules' => [

        'roxymce' => [
            'class' => 'navatech\roxymce\Module',
            'uploadFolder' => '@frontend/web/uploads/images',
            'uploadUrl' => 'http://localhost:8080/yiia/advanced/frontend/web/uploads/images',
        ],

    ],
````
and tell me the result?

**Comment by FarshidShekari** [comment]
I have upload folder in root directory and set urls to it. I changed like this:
```
 'modules' => [

        'roxymce' => [
            'class' => 'navatech\roxymce\Module',
            'uploadFolder' => '../../uploads/images',
            'uploadUrl' => 'http://localhost:8080/yiia/advanced/uploads/images',
        ],

    ],
```
with your changes but not worked and give messages:
![sketch](https://user-images.githubusercontent.com/6597508/33494209-befd725c-d6d7-11e7-962c-895b7ee4123a.png)

**Comment by phuongdev89** [comment]
@fantom0 please understand, `uploadFolder` using Yii::getAlias() for located the folder path, so you have to define it start with @ symbol.
`../../uploads/images` was not accepted.
`http://localhost:8080/yiia/advanced/uploads/images` means you must have .htaccess file and rewrite the url to root folder, it's not secure.

**Comment by FarshidShekari** [comment]
Ok, I changed my config file module section to:
```
'roxymce' => [
            'class' => 'navatech\roxymce\Module',
            'uploadFolder' => '@app/web/uploads/images',
            'uploadUrl' => '/uploads/images',
        ],
```

but when I want to upload a file, show me an alert about "something went wrong" and don't show any error in console.

**Comment by phuongdev89** [comment]
@fantom0 no, you are using yii2-advanced, there is no folder named `app`, only `frontend` and `backend`

**Comment by FarshidShekari** [comment]
Ok, I used `@frontend` instead of `@pp`, file uploaded but don't save it and  I get  `"something went wrong"`  message in the alert and How to change file size?

**Comment by FarshidShekari** [comment]
@phuong17889

**Comment by FarshidShekari** [comment]
If you can't, please tell me.
@phuong17889

**Comment by phuongdev89** [comment]
@fantom0 nobody encountered that error like you, could you please share your project to github, so I can help?

**Comment by FarshidShekari** [comment]
I showed my codes to you, but still, you want I upload my project to GitHub?
@phuong17889

**Comment by FarshidShekari** [comment]
When I want to upload file occurred this error:
![sketcqh](https://user-images.githubusercontent.com/6597508/33727958-2fb7c03c-db8e-11e7-9234-33a5b1f80485.png)

**Comment by FarshidShekari** [comment]
{"name":"Invalid Configuration","message":"The fileinfo PHP extension is not installed.","code":0,"type":"yii\\base\\InvalidConfigException","file":"C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\yiisoft\\yii2\\helpers\\BaseFileHelper.php","line":144,"stack-trace":["#0 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\yiisoft\\yii2\\validators\\FileValidator.php(358): yii\\helpers\\BaseFileHelper::getMimeType('C:\\\\xampp\\\\tmp\\\\ph...', NULL, false)","#1 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\yiisoft\\yii2\\validators\\FileValidator.php(251): yii\\validators\\FileValidator->validateExtension(Object(yii\\web\\UploadedFile))","#2 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\yiisoft\\yii2\\validators\\FileValidator.php(208): yii\\validators\\FileValidator->validateValue(Object(yii\\web\\UploadedFile))","#3 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\yiisoft\\yii2\\validators\\Validator.php(267): yii\\validators\\FileValidator->validateAttribute(Object(navatech\\roxymce\\models\\UploadForm), 'file')","#4 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\yiisoft\\yii2\\base\\Model.php(360): yii\\validators\\Validator->validateAttributes(Object(navatech\\roxymce\\models\\UploadForm), Array)","#5 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\navatech\\yii2-roxymce\\src\\models\\UploadForm.php(48): yii\\base\\Model->validate()","#6 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\navatech\\yii2-roxymce\\src\\controllers\\ManagementController.php(263): navatech\\roxymce\\models\\UploadForm->upload('C:\\\\xampp\\\\htdocs...')","#7 [internal function]: navatech\\roxymce\\controllers\\ManagementController->actionFileUpload('C:\\\\xampp\\\\htdocs...')","#8 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\yiisoft\\yii2\\base\\InlineAction.php(57): call_user_func_array(Array, Array)","#9 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\yiisoft\\yii2\\base\\Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)","#10 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\yiisoft\\yii2\\base\\Module.php(528): yii\\base\\Controller->runAction('file-upload', Array)","#11 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\yiisoft\\yii2\\web\\Application.php(103): yii\\base\\Module->runAction('roxymce/managem...', Array)","#12 C:\\xampp\\htdocs\\yiia\\advanced\\vendor\\yiisoft\\yii2\\base\\Application.php(386): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))","#13 C:\\xampp\\htdocs\\yiia\\advanced\\backend\\web\\index.php(17): yii\\base\\Application->run()","#14 {main}"]}

**Comment by phuongdev89** [comment]
Hi, seems you are using windows with xampp stack, and fileinfo is not installed.
With my experience, xampp, wamp, appserv is not compatibility for yii development.
You should try ampps.com, will work better.

**Comment by FarshidShekari** [comment]
Are you sure?
Why doesn't it work in xampp?

**Comment by FarshidShekari** [comment]
Now I use Ampps, I can now upload files but don't show existing files in the directory.

**Comment by phuongdev89** [comment]
Try to clear your @runtime/logs/app.log
Then run again, if still error and it is appear in app.log, paste it here

**Comment by FarshidShekari** [comment]
I delete but, that's not solution. :(

**Comment by phuongdev89** [comment]
have a skype and teamviewer?
add my skype `yeu1708` and I will be available next 3 hours from now.

**Comment by vitatheresia** [comment]
Hi @FarshidShekari , @phuong17889 , can you help me? i've case same like this, but not solved now. 
Thank you guys
