### ISSUE TITLE
trouble with install

### ISSUE THREAD

**Issue by Marcuzzz** [navatech/yii2-roxymce#18]
`    	'roxymce' => [
            'class' => 'navatech\roxymce\Module',
            'uploadFolder' => '@app/web/uploads/images',
            'uploadUrl' => '/uploads/images',
        ],
`

Bad Request (#400)
Missing required parameters: type

<img width="675" alt="screen shot 2018-01-10 at 16 15 03" src="https://user-images.githubusercontent.com/7437046/34779826-96459e52-f621-11e7-8672-f7352db71151.png">

**Comment by phuongdev89** [comment]
hi @Marcuzzz,
Roxymce was not made for direct use.
If you still want access it directly, follow this code
```
<iframe src="<?= Url::to([
	'/roxymce/default',
	'type'   => 'image',
	'input'  => 'fieldID2',
	'dialog' => 'modal',
]) ?>" height="470px" width="100%"></iframe>
```
you must define param `type`, `dialog` in your url, it seems like `http://domain.local/roxymce/default?type=image&dialog=modal`

**Comment by Marcuzzz** [comment]
ok thx. Another way was to $type = "" in the controller:

`class DefaultController extends Controller {

	/**
	 * Render a view
	 *
	 * @param $type
	 *
	 * @return string
	 */
	public function actionIndex($type = "") {
`

If I want to change some things and add a button, what would be the easiest way to accomplish this.
I would like to extend this "module" and add things.

I created a new module and was trying something like this in a controller:

`
<?php
namespace backend\modules\filemanager\controllers;
use navatech\roxymce\controllers\DefaultController;

class FilemanagerController extends DefaultController {}
`

Kind regards,
Marc
