### ISSUE TITLE
I would like to change the widget 

### ISSUE THREAD

**Issue by Marcuzzz** [navatech/yii2-roxymce#2]
I would like to change the widget to a simple textInput with a button to open the file Insert link or Insert image window

View image:
http://i.imgur.com/esk9j7k.png
So a simple textinput

This would be even better view image:
http://i.imgur.com/Sr1mGXQ.png

Can you tell me if this is possible?
Thx

**Comment by phuongdev89** [comment]
Yes, it's possible.
But this is roxymce, which stands for "Roxy file manager & Tinymce"
So maybe I'll make another version without tinymce.
Thanks for your idea.

**Comment by Marcuzzz** [comment]
Would be nice!
