### ISSUE TITLE
Update attributes after renaming select file

### ISSUE THREAD

**Issue by nick-denry** [navatech/yii2-roxymce#23]
Hi!

Bug description: After renaming the file fancyboxfile preview data and download button link url are wrong.

How to reproduce: rename any file and open preview and click download button.

Fancybox attributes and download button link url should be updated after renaming an selected file.

I've created pr for this https://github.com/navatech/yii2-roxymce/pull/22

**Comment by phuongdev89** [comment]
Yes, maybe I never have encountered that error.
Thanks
