### ISSUE TITLE
Add doubleclick event on selected file

### ISSUE THREAD

**Issue by nick-denry** [navatech/yii2-roxymce#24]
Hi! 
Could we add subj? Doubleclick event like event "file selected" via select button. 

If yes, I'll create a pr.

**Comment by phuongdev89** [comment]
Yes please, thanks

**Comment by nick-denry** [comment]
PR https://github.com/navatech/yii2-roxymce/pull/25

**Comment by nick-denry** [comment]
I want to make yet some commits (like docs markup update) so maybe you could not create release after merging this PR?

**Comment by nick-denry** [comment]
Thank you.
