### ISSUE TITLE
Composer Install not update source

### ISSUE THREAD

**Issue by khacnha** [navatech/yii2-roxymce#4]
Code file module.php when install composer:
`foreach ($config as $key => $value) {
            if (!array_key_exists($key, $this->config)) {
                $this->config[$key] = $value;
            }
            define($key, $value);
        }`
not updated as on github:
`foreach ($config as $key => $value) {
            if (!array_key_exists($key, $this->config)) {
                $this->config[$key] = $value;
            }
        }
        foreach ($this->config as $key => $value) {
            if (!defined($key)) {
                define($key, $value);
            }
        }`

**Comment by phuongdev89** [comment]
make sure you've installed 04245a5359a67749e121f432f61b36ce05b24eac version.
can attach your `composer.lock`?
or open it and find something look like this:

```
            "name": "navatech/yii2-roxymce",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/navatech/yii2-roxymce.git",
                "reference": "04245a5359a67749e121f432f61b36ce05b24eac"
            },
```

**Comment by khacnha** [comment]
I installed according to instructions:
`composer require navatech/yii2-roxymce "@dev"`
and here's the code in the file composer.lock:
`"name": "navatech/yii2-roxymce",
            "version": "1.0.4.1",
            "source": {
                "type": "git",
                "url": "https://github.com/navatech/yii2-roxymce.git",
                "reference": "3c448dd31be4a997763b025903251fa5a1f5e418"
            },`

P/S: how to integrate into multiple files and file input type or text input type?

**Comment by phuongdev89** [comment]
As I said `make sure you've installed 04245a5 version.`
Your problem maybe same https://github.com/composer/composer/issues/858

please run `composer update` again or try alternative way:

```
Or add to require section of composer.json then run composer update
"navatech/yii2-roxymce" : "@dev" 
```

Let's me know if still error.

It was made for tinymce4 only, so you can try this:
http://demos.krajee.com/widgets#fileinput
