### ISSUE TITLE
Error About yiisoft/yii2-app-advanced

### ISSUE THREAD

**Issue by khacnha** [navatech/yii2-roxymce#5]
{
    "name": "yiisoft/yii2-app-advanced",
"require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.6",
        "yiisoft/yii2-bootstrap": "_",
        "yiisoft/yii2-swiftmailer": "_",
        "navatech/yii2-roxymce": "@dev"
    },
}
Error follow:
PHP Strict Warning – yii\base\ErrorException

Declaration of navatech\roxymce\helpers\FileHelper::getMimeType() should be compatible with yii\helpers\BaseFileHelper::getMimeType($file, $magicFile = NULL, $checkExtension = true)

**Comment by phuongdev89** [comment]
you should exclude E_STRICT from error_reporting in php.ini
