### ISSUE TITLE
Bug preventing from getting the valid directory for uploaded files

### ISSUE THREAD

**Issue by logofakt** [navatech/yii2-roxymce#7]
Hi,

there seems to be a bug in both Module.php and RoxyHelpers.php which prevents from getting the valid base directory for uploaded files.

Modules.php line 85:
replace
$FilesRoot = RoxyHelper::fixPath(RoxyHelper::getBasePath() . RoxyHelper::getFilesPath());
with
$FilesRoot = RoxyHelper::fixPath(RoxyHelper::getFilesPath());

RoxyHelpers.php static function getFilesPath() line 204
replace
$ret = FileHelper::fixPath(RoxyHelper::getBasePath() . Yii::getAlias('@web/') . FILES_ROOT);
with
$ret = FileHelper::fixPath(Yii::getAlias('@web/') . FILES_ROOT);

otherwise the basePath or @web would be doubled.

Regards Christian

**Comment by phuongdev89** [comment]
hi @logofakt 
Master branch has discontinued because bug from roxyfileman.
I'm trying to develop new version that not depended on roxyfileman.
Sorry about this convenient.

**Comment by phuongdev89** [comment]
Hi @logofakt 
please try new release version 2.0.0.0
